# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_add', models.IntegerField()),
                ('performed_sub', models.IntegerField()),
                ('performed_mul', models.IntegerField()),
                ('performed_div', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('skill_add', models.IntegerField()),
                ('skill_sub', models.IntegerField()),
                ('skill_mul', models.IntegerField()),
                ('skill_div', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
    ]
