# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0002_auto_20170715_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
    ]
